# Generated by Django 4.2.8 on 2025-08-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starterthree', '0001_initial'),
    ]

    operations = [
    ]
